### ISSUE TITLE
Error when evaluate the risquette

### ISSUE THREAD

**Issue by NicolasGeraud** [huitparfait/huitparfait#61]
Hi,

My pronostic for France-Roumanie was FR 2-1 RO and 2 points on the risquette.
I was wrong on the risquette : 
"Risquette fausse : Au moins un but dans les 10 premières minutes"

But my score is : 7 pts : 5 pts + 2 pts (risquette) 

I think I should have 5 pts - 2 pts => 3 pts

**Comment by mghignet** [comment]
Hi Nicolas!

Thanks for your feedback.
If I'm not mistaken you answered "false" to the risquette. the event did not happen (no goal during the first 10 minutes of the match) so you were right and you earned those points.
This is a UI issue were the result of the risquette ("Risquette Vraie" or "Risquette fausse") is about whether it happened or not, not whether you were right or not.

We have to work on the wording beause you're not the only one being confused.

Thanks!
