### ISSUE TITLE
improve UI for the risquette result

### ISSUE THREAD

**Issue by NicolasGeraud** [huitparfait/huitparfait#65]
The UI is very confusing about the result of a risquette.
![A successful risquette](https://www.dropbox.com/s/cezuxq5bafwe966/Screenshot_20160611-130008.png?dl=0)

The screenshot above seems to represent a wrong pronostic, but it's not.

**Comment by NicolasGeraud** [comment]
duplicate #63 
sorry

**Comment by mghignet** [comment]
No problem
