### ISSUE TITLE
Update ranking right after match ended

### ISSUE THREAD

**Issue by iamvdo** [huitparfait/huitparfait#70]
It's fun to update ranking every day at 8:08, but how about update it after match ended ?
It's better for dynamic real-time interactions between group members imo. ;)

**Comment by mghignet** [comment]
Hi!

This was set up for two main reasons : 
- It's fun :) and people talk about their results when arriving at work!
- It gives us time to input scores

With more time we would have liked to let users input the right score when a match has ended (with some controls obviously, to get the right score).

Thanks for your feedback!
